---
LUpBSvN1a50: The Animals - We've Gotta Get Out Of This Place (1965) slideshow
4V1p1dM3snQ: Louie Louie - The Kingsmen  (HQ)
6gV9gUeFHIw: Chopin - Valentina Igoshina - Prelude Op. 28, No. 15
8dOWE2Xb2Xw: Beethoven- Piano Sonata No. 1 in F minor, Op. 2 No. 1- 2nd mov. Adagio
9E6b3swbnWg: Chopin - Nocturne op.9 No.2
b6YWZKfvpho: SYREETA WRIGHT - HARMOUR LOVE
i-BFLjyIb04: The Antlers - Two
InRDF_0lfHk: Paint it Black - Vietnam War
IRfzAWUf3W4: Iris DeMent - Our Town
jRHQPG1xd9o: VULFPECK /// 1612
k35haKwqY14: Gillian Welch - Hard Times
mgHxmAsINDk: Beethoven - 7th Symphony - 2nd movement
nfWlot6h_JM: Taylor Swift - Shake It Off
nT7_IZPHHb0: Beethoven-Moonlight Sonata (Mvt. 1)
pAgnJDJN4VA: AC/DC - Back In Black
qkIyvA_iJnw: Tchaikovsky - 5th Symphony, Op. 64 - 2nd movement  - Andante Cantabile
QOUVVccs5dc: Bruce Springsteen - Highway Patrolman
UlyprQrZz4U: Excision & Space Laces - Destroid 10 Funk Hole VIP
wJVpihgwE18: The Animals - We Gotta Get Out Of This Place
XftabV9S2z0: Introducing . . . VULFPECK (Outro)
XivELBdxVRM: Ella Fitzgerald - Summertime (High Quality - Remastered)
ZsXKa97J6pM: The Antlers - "Two" (Official Music Video)
fbGUEelmzxo: Noah and the Whale - 'L.I.F.E.G.O.E.S.O.N.' (Official Video)
9qZOOb02u-4: Orphan Girl - Gillian Welch.wmv
